---
title: Install Guide for Java EE
template: page.html
---

== Using the latest snapshots

The MVC specification and Ozark are under active development. Therefore, we recommend to use the latest 
snapshots for your experiments. This will ensure, that you are using the latest version of both the API 
and the implementation.

Sonatype OSS snapshot repository

To get the latest snapshots for your project, you will have to add 
the https://oss.sonatype.org/content/repositories/snapshots[Sonatype OSS snapshot repository] to your POM. 
To do so, just add the following configuration to your `pom.xml`:

[source,xml]
----
<repositories>
    <repository>
        <id>sonatype-oss-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
----

By adding this repository to your POM, you will be able to use the snapshot versions of the various artifacts:

* **Specification:**
** Stable version: `{{versions.spec.latest}}`
** Snapshot version: `{{versions.spec.develop}}`
* **Ozark (RI):**
** Stable version: `{{versions.ozark.latest}}`
** Snapshot version: `{{versions.ozark.develop}}`
