---
title: Install Guide for Java EE
template: page.html
---

== Install Guide for Java EE

MVC is built on top of JAX-RS. This means that Ozark can be run on most application servers without 
any additional configuration. You will just need to include the MVC API JAR as well as the Ozark module 
for the JAX-RS implementation shipped with your application server.

Ozark requires at least the Java EE 8 Web-Profile or the Eclipse MicroProfile.

NOTE: The MVC specification and Ozark are under active development. Therefore, we recommend to use the latest 
snapshots for your experiments. This will ensure, that you are using the latest version of both the API 
and the implementation. Please refer to link:install-snapshots.html[Using the latest snapshots] to learn more. 

=== Required dependencies

The dependencies you need to add to your `pom.xml` file depend on which application server your are using.

==== Glassfish/Payara

Glassfish comes with Jersey as its JAX-RS implementation. Please add the following dependencies to your 
application:

[source,xml]
----
<dependency>
    <groupId>javax.mvc</groupId>
    <artifactId>javax.mvc-api</artifactId>
    <version>{{versions.spec.latest}}</version>
</dependency>
<dependency>
    <groupId>org.mvc-spec.ozark</groupId>
    <artifactId>ozark-jersey</artifactId>
    <version>{{versions.ozark.latest}}</version>
</dependency>
----

==== Wildfly and JBoss EAP

Wildfly is using RESTEasy for JAX-RS. So you need to Ozark RESTEasy integration module:

[source,xml]
----
<dependency>
    <groupId>javax.mvc</groupId>
    <artifactId>javax.mvc-api</artifactId>
    <version>{{versions.spec.latest}}</version>
</dependency>
<dependency>
    <groupId>org.mvc-spec.ozark</groupId>
    <artifactId>ozark-resteasy</artifactId>
    <version>{{versions.ozark.latest}}</version>
</dependency>
----

==== Thorntail

We currently have a experimental fraction for thorntail, but you too can use the JAX-RS fraction and add
the same dependencies as required for thorntail:

[source,xml]
----
<dependency>
    <groupId>io.thorntail</groupId>
    <artifactId>jaxrs</artifactId>
</dependency>
<dependency>
    <groupId>javax.mvc</groupId>
    <artifactId>javax.mvc-api</artifactId>
    <version>{{versions.spec.latest}}</version>
</dependency>
<dependency>
    <groupId>org.mvc-spec.ozark</groupId>
    <artifactId>ozark-resteasy</artifactId>
    <version>{{versions.ozark.latest}}</version>
</dependency>
----

using fraction :

[source,xml]
----
<dependency>
    <groupId>io.thorntail</groupId>
    <artifactId>mvc</artifactId>
</dependency>
----

==== Apache TomEE

Apache TomEE uses CXF as the JAX-RS implementation. Unfortunately there are some known bugs in CXF 
which are causing trouble for Ozark. The latest CXF release should fix these issues, but 
Apache TomEE currently ships with an older CXF release.

If you want to give Ozark on Apache TomEE a try, add the following dependencies to your `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>javax.mvc</groupId>
    <artifactId>javax.mvc-api</artifactId>
    <version>{{versions.spec.latest}}</version>
</dependency>
<dependency>
    <groupId>org.mvc-spec.ozark</groupId>
    <artifactId>ozark-core</artifactId>
    <version>{{versions.ozark.latest}}</version>
</dependency>
----

If using CXF with Ozark is causing trouble, you can also manually add RESTEasy to your application and 
use this instead of CXF. To do so, use the following depndencies instead.

[source,xml]
----
<dependency>
    <groupId>javax.mvc</groupId>
    <artifactId>javax.mvc-api</artifactId>
    <version>{{versions.spec.latest}}</version>
</dependency>
<dependency>
    <groupId>org.mvc-spec.ozark</groupId>
    <artifactId>ozark-resteasy</artifactId>
    <version>{{versions.ozark.latest}}</version>
</dependency>
<dependency>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-cdi</artifactId>
    <version>3.6.1.Final</version>
</dependency>
<dependency>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-servlet-initializer</artifactId>
    <version>3.6.1.Final</version>
</dependency>
<dependency>
    <groupId>org.jboss.resteasy</groupId>
    <artifactId>resteasy-validator-provider-11</artifactId>
    <version>3.6.1.Final</version>
</dependency>
----

That's all. Now you can start developing your first MVC 1.0 application.
